### ISSUE TITLE
Use UInt/ULong for unsigned numeric values

### ISSUE THREAD

**Issue by rock3r** [mpgirro/stalla#35]
We are using `Int` and `Long` to represent unsigned values (such as the season and episode number, or the enclosure length). We should likely switch to using `UInt` and `ULong` to avoid issues, but the Java API story may be a bit worse because of it. On the other hand, we can prevent incorrect values from getting represented in the first place, which would be an enormous win.

What do you think @mpgirro ?

**Comment by mpgirro** [comment]
Good point. Unsigned values are a definite win, and the Java aspect is the definite pain point in all this.

Let's take the season number for example. In the builder, we can simply provide overloaded methods by exposing a `season(season: UInt?)` as well as a `season(season: Int?)`. So we still provide a Java-friendly variant and don't have to struggle with a Kotlin `UInt` type from the client side. 

From the model perspective, we also have to cope with the fact that – as ill advised as it may be for a Java client – it's still possible to instantiate a data class instance directly. We can expand all model classes in question with secondary constructors that take `Int` types for compatibility. 

The question that remains then is: What are we to do with any signed integer values we receive that are smaller than `0`? I see three options: Setting them to `null`, `0` or their absolute value. In generally, I'd tend to simply `null` them. The enclosure length however is a mandatory field, so this is not a viable option. Setting the values to `0` might lead to semantic issues within the clients. We could argue that the mathematical absolute at least always results in a "proper" number ("if we encounter an unrealistic number like -47, then 47 is good enough as well, and maybe even what was intended in the first place" – something like that). But the absolute doesn't really fix the issue itself as well, of course.

**Comment by rock3r** [comment]
Agreed on the Java interop story, both the builders and models overloads seem sensible. When parsing numbers, regardless if they're mandatory, we should probably refuse the value when it's negative, just like we'll need to do in the Java-friendly `Int` overloads. This means using something like `require(value == null || value >= 0) { "Only positive values are acceptable" }`. In turn, this implies refusing to parse a feed that contains a negative enclosure length... it is formally invalid, after all.

At that point though, we should make sure we throw exceptions (with meaningful error messages) explaining the issue when some mandatory value didn't pass muster, rather than returning `null` when trying to parse something invalid. Failing silently doesn't seem like a great option anyway when parsing — we can always easily provide a `parseOrNull()` variant, if that functionality is needed.

**Comment by mpgirro** [comment]
We forgot about the getter return types of the model classes. They'll still be Kotlin `UInt`. I guess we'll either have to write an extension that allows something like `.getSeason().toInt()` or provide an additional getter a la `.getSeasonAsInt()`. I am not to fond of both, but don't have a better idea right now.

**Comment by rock3r** [comment]
`UInt` and `ULong` already have `toInt()` and `toLong()` functions, so that'd be taken care at least. I suppose if Java folks want to use non-unsigned numbers, the API's there

**Comment by mpgirro** [comment]
Ok, I thought they don't exist because it seems I'm unable to see them within our Java tests:

<img width="637" alt="Screenshot 2021-02-08 at 13 13 35" src="https://user-images.githubusercontent.com/589073/107218145-826a7280-6a0f-11eb-9166-186a57cf9a5f.png">

However, the Kotlin [stdlib API reference](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-u-int/to-int.html) clearly states that such methods should be available.

I feel like I'm missing something obvious here 🤔

**Comment by rock3r** [comment]
Same here. Let me ask around internally (advantages of working at JetBrains 😉)

**Comment by rock3r** [comment]
My understanding is that _right now_ interop with Java is complicated because those methods are getting mangled — this would need `@JvmName` annotations, but they're in the stdlib, so the only solution would be to wrap them in our own method. This is not great; I'm trying to understand whether this is something that will change in the future or not. Probably should pause this for now.

**Comment by mpgirro** [comment]
Ok, thanks for the update

**Comment by mpgirro** [comment]
[Kotlin 1.5.0-M1](https://github.com/JetBrains/kotlin/releases/tag/v1.5.0-M1) is available. Unfortunately nothing about this issue in the changelog 😭

**Comment by rock3r** [comment]
I just checked, it's unlikely that they're doing it for 1.5 :(

**Comment by mpgirro** [comment]
🙁, but thanks for checking :)

**Comment by rock3r** [comment]
No worries. I will try to push it for 1.6...

**Comment by rock3r** [comment]
1.5.0 RC is out. Unsigned numbers are [now stable](https://kotlinlang.org/docs/basic-types.html#unsigned-integers); we should check if they're still mangled from Java, which would be silly IMO

**Comment by mpgirro** [comment]
Looks like they still get mangled 😕

<img width="344" alt="Screenshot 2021-04-16 at 12 50 12" src="https://user-images.githubusercontent.com/589073/115014468-a4222300-9eb2-11eb-8790-2cc7d6ed1246.png">

**Comment by rock3r** [comment]
I'll open an issue

**Comment by rock3r** [comment]
Looks like with Kotlin 1.5.0 we can annotate methods with `@JvmName` to opt them in to interop, so this may actually be feasible now! See the [KT-46144](https://youtrack.jetbrains.com/issue/KT-46144) issue for more details.

**Comment by mpgirro** [comment]
That's interesting. Thanks for inquiring this! :)

**Comment by rock3r** [comment]
Well, after the discussion with Roman there, I'd say he has a point; let's not use unsigned ints for this. You ok for closing the issue?

**Comment by mpgirro** [comment]
Fine with that, he has a point there.
