### ISSUE TITLE
Changes to Google Play

### ISSUE THREAD

**Issue by mpgirro** [mpgirro/stalla#44]
The [RSS feed guidelines for Google Podcasts](https://support.google.com/podcast-publishers/answer/9889544?visit_id=637488295141863525-3627953742&rd=1#zippy=%2Crecommended-categories) is very unspecific with respect to categories. Unlike the iTunes specification (see PR #42), the document merely recommends certain category value.

However, there exits an [XSD document](https://www.google.com/schemas/play-podcasts/1.0/play-podcasts.xsd) for the Google Play namespace. The element documentation states that the category values from the support document are to be treated as the only possible values:

- [x] Restrict to predefined values.
- [x] Do not provide a hierarchy, since unlike iTunes, such are not defined.
- [ ] ~Migrate from `List` to `Set`~
- [x] Add `author` to Episode
- [x] Add dedicated type for `explicit` element with possible states: `yes`, `no` and `clean`
- [x] Add `newFeedUrl` to Podcast
- [x] Add `email` to Podcast

**Comment by rock3r** [comment]
Good spot on the XSD. Based solely on the docs, I had so far assumed it was the same as iTunes categories, which it isn't really. Go figure why Google Play decided to do things this different (and poorly documented)...

**Comment by mpgirro** [comment]
Yes, the Google Play namespace is very poorly documented indeed.

**Comment by mpgirro** [comment]
There are actually a few additional things defined in the XSD:

* The `author` is also specified on the item level
* The `explicit` element has three possible states: `yes`, `no` and `clean`
* `newFeedUrl` element on the channel level

**Comment by mpgirro** [comment]
Done
