### ISSUE TITLE
Refine factory APIs

### ISSUE THREAD

**Issue by mpgirro** [mpgirro/stalla#45]
We are providing certain methods an all models/builder/companions for a consistent library experience. I've noticed an ambiguity in the API that I'd like to sort out before we release a stable API. All companion objects are treated as factories, because they provide respective methods for the class they belong to.

There are these cases right now:

1. Model classes provide a factory companion that implement the `BuilderFactory` interface. Therefore, a factory companion provides a (static) method `builder()` that returns a builder implementation of the respective model.
2. Every builder implementation is a subtype of the `Builder` interface. Therefore they provide a method `builder.from(prototype)`. Note that `from` is a method on the builder instance and not the factory companion. This way, we can do something that resembles prototype pattern in order to easily configure a builder by doing: `builder = Model.builder().from(modelPrototype)`.
3. Right now, we also provide (static) methods `from(string)` in the factory companions of custom enumeration (or sealed class) types (`ShowType`, `EpisodeType`, `TranscriptType`, `ItunesCategory`, soon also `GoogleplayCategory`). In contrast to the `from` methods of builder instances, the `from` methods of type factories do not mutate the calling instance (because it's the factory companion), but produces an instance of the type itself. 

I am proposing a change in the method names, by renaming the `from` of the enumerable types to `of` (I know you've just changed that recently @rock3r, sorry about the revert request). We can also create a common supertype similar to `BuilderFactory` to enforce a respective method in every type companion (`TypeFactory` ?). We'd have to settle for a common name for the string argument then, on that describes the argument in every case.

What do you think?

**Comment by rock3r** [comment]
Good point on the naming clash. But I'd like to propose a slightly different implementation. What if we renamed the Builder#from method to something more representative, such as applyFrom? After all, if it's mutating the instance instead of creating a new one, applyFrom seems more appropriately describing the behaviour. 

Alternatively, we could see it to make the Builder#from create a new instance of the builder from a model (or, alternatively, move the functionality to the model with a toBuilder instance method). Thoughts?

**Comment by mpgirro** [comment]
I am fine with renaming it. We can also simply call it `apply`, since the documentation already states:

```
* Applies the properties of [model] to this builder.
```

I rather not have the method return a new instance though. That was my first approach, but actually I except the most heavy use will be in a call chain like `.builder().from(model)`. Then the first `.builder()` call creates an instance, and then the `.from(...)` call creates another one, making the first instantiation rather a waste.

**Comment by rock3r** [comment]
The reason I am suggesting `applyFrom` is that, in Kotlin, `apply` already does exist in the stdlib and has a different (although somewhat related) meaning. I think the former would clear up any ambiguity.

I see the reasoning on not going for new instances, you have a good point 👍

**Comment by mpgirro** [comment]
I expected you'd argue like that 😅. 

Let's go with `applyFrom` 👍. I'll do the changes tomorrow.

**Comment by rock3r** [comment]
Eheh sorry if I'm being a bit of a pain 😅

**Comment by mpgirro** [comment]
Don't worry, your argument is the better one. I was just trying to sneak in a "nicer" looking name 😅

**Comment by rock3r** [comment]
I _may_ be a stickler for consistency 😅😁

**Comment by mpgirro** [comment]
And that's a good thing. Nothing more frustrating than inconsistency 👍

**Comment by mpgirro** [comment]
Done. A renaming endeavour that did not break anything for once 😅

**Comment by rock3r** [comment]
Good thing we have tests :D
