### ISSUE TITLE
Multiple Person constructs

### ISSUE THREAD

**Issue by mpgirro** [mpgirro/stalla#58]
Right now, we have a `Person` class that we use for Atom author, Atom contributor and iTunes owner. This has some implications:

* The Atom author/contributor have `name`, `email` and `uri` defined, so the current `Person` class is basically an Atom Person.
* The iTunes owner has `name` and `email` defined in the [spec](https://help.apple.com/itc/podcasts_connect/#/itcb54353390). Since we reuse our current `Person`, clients can also define an `uri` field as well. This gets written to the feed as `<itunes:uri>` which is undefined however.
* Podcastindex phase 2 (closed now) defines a new [person](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#person) construct that looks completely different from our current `Person`.

I am proposing to split up the current `Person` class into an `AtomPerson` and an `ItunesOwner` **before** the v1.0 release. First to ensure that we do not allow to write undefined constructs for the iTunes namespace, and second to make room for a future `PodcastindexPerson`.

I am also not sure if we should provide a common `PersonBase` interface for `AtomPerson` and `ItunesOwner`, since this interface will not be the foundation for the `PodcastindexPerson`, and we don't really have another benefit from it either.

What do you think @rock3r ?

**Comment by rock3r** [comment]
Makes perfect sense to me to split, but I don't see a reason to extract an interface at this point given it would be used for semantically unrelated things

**Comment by mpgirro** [comment]
Then I'll add this change in my current cleanup/fixing spree branch.
