### ISSUE TITLE
Deprecate PodcastBuilder.podcastPodcastindexBuilder property

### ISSUE THREAD

**Issue by mpgirro** [mpgirro/stalla#89]
The `PodcastBuilder` interface exposes a property by the name `podcastPodcastindexBuilder`. To be consistent in our naming schema, this property should simply be called `podcastindexBuilder`. 

This is an API-breaking change and should be implemented in a yet unplanned release when breaking changes will be allowed.

**Comment by rock3r** [comment]
We should have a deprecation window for the property; doing a rename in 1.x (maybe even 1.1), with an appropriate `ReplaceWith` in place. Schedule it for deletion in 2.0, mark it as such in the deprecation notice, and then go along until 2.0 is here.

**Comment by rock3r** [comment]
We can also use [`org.jetbrains.annotations.ApiStatus.ScheduledForRemoval(inVersion = "2.0.0")`](https://github.com/JetBrains/java-annotations/blob/master/common/src/main/java/org/jetbrains/annotations/ApiStatus.java#L87) to explicitly mark the version when we're dropping it

**Comment by mpgirro** [comment]
Looks like `@ScheduledForRemoval` isn't applicable in this case. We need to annotate the interface member, and the annotation requires a backing field or delegate (Kotlin supports neither in interfaces).

**Comment by rock3r** [comment]
Ah, dang it.  Well, was worth a try :)

**Comment by rock3r** [comment]
Looks like this was done in  #93
